export const CHANGE_CURRENT_MUSIC = "player/CHANGE_CURRENT_MUSIC";
export const CHANGE_PLAY_LIST = "player/CHANGE_PLAY_LIST";
export const CHANGE_CURRENT_MUSIC_INDEX = "player/CHANGE_CURRENT_MUSIC_INDEX";

export const CHANGE_SEQUENCE = "player/CHANGE_SEQUENCE";

export const CHANGE_LYRIC_LIST = "player/CHANGE_LYRIC_LIST";
export const CHANGE_CURRENT_LYRIC_INDEX = "player/CHANGE_CURRENT_LYRIC_INDEX"; 